// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRGrreSMjjvppTuA1LlyXIwbCUzgJVPAA',
    appId: '1:661641114119:web:d52d4e5550c287be2530a2',
    messagingSenderId: '661641114119',
    projectId: 'class-connect-bfa3a',
    authDomain: 'class-connect-bfa3a.firebaseapp.com',
    storageBucket: 'class-connect-bfa3a.appspot.com',
    measurementId: 'G-ZNQMV3H7R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP4SsjAg8wArFwknuKjLJdayOHUYc8pAY',
    appId: '1:661641114119:android:3ef5c5f9d07986a82530a2',
    messagingSenderId: '661641114119',
    projectId: 'class-connect-bfa3a',
    storageBucket: 'class-connect-bfa3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSzSUPhSpnHL9ojZQANNytuY0pFrzdiOg',
    appId: '1:661641114119:ios:2e945ccedf8fe1962530a2',
    messagingSenderId: '661641114119',
    projectId: 'class-connect-bfa3a',
    storageBucket: 'class-connect-bfa3a.appspot.com',
    iosBundleId: 'com.neuralcompute.classconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSzSUPhSpnHL9ojZQANNytuY0pFrzdiOg',
    appId: '1:661641114119:ios:c9d4e962343e39122530a2',
    messagingSenderId: '661641114119',
    projectId: 'class-connect-bfa3a',
    storageBucket: 'class-connect-bfa3a.appspot.com',
    iosBundleId: 'com.neuralcompute.classconnect.RunnerTests',
  );
}
